// auto generated by enum2str_gen.py, modify it if needed
#ifndef ENUM_2_STR_H__
#define ENUM_2_STR_H__
#define ENUM2STR(...) enum2str(__VA_ARGS__).data()

#include <string>
#include "./example/a.h"
std::string enum2str(A e);
#include "./example/b.h"
std::string enum2str(B e);
#include "./example/e/ee.h"
std::string enum2str(EE e);
#endif  // ENUM_2_STR_H__
